import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import metaverse from '../public/metaverse.jpeg';
import Meta from '../public/meta.svg';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import { useRouter } from 'next/router';
import { motion } from 'framer-motion';

export default function Home() {
  const router = useRouter();
  // Formik Logic
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: 'United States',
      terms: "",
    },
    // Validation
    validationSchema: Yup.object({
      name: Yup.string().max(20, 'Name must be 20 characters or less.').required('Name is required.'),
      email: Yup.string().email('Invalid email address').required('E-Mail is required.'),
      terms: Yup.array().required('Terms of service must be checked')
    }),
    // Submit Form
    onSubmit: (values) => {
      console.log("Form Submitted");
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });
  console.log(formik.errors);

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute w-full">
      <Head>
        <title>Enter The Metaverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form onSubmit={formik.handleSubmit} className="bg-white/75 shadow-2xl
         flex rounded-lg lg:w-2/3 lg:h-9/10 font-avenirRoman">
          <div className="flex-1 text-gray-800 p-10">
            <Link href="/">
              <div className="flex items-center justify-between h-14 w-14 rounded-lg">
                <Image className="h-full" src={Meta} alt="Meta Logo" />
                <div className="flex flex-col px-2 pt-2">
                  <span className="text-5xl font-avenirRoman">Meta</span>
                </div>
              </div>
            </Link>
            <h1 className="text-2xl lg:pb-2 lg:mt-5 font-avenirRoman">Enter The Metaverse</h1>
            <p className="text-sm text-slate-600 font-avenirBook">We’re moving beyond 2D screens and into immersive experiences in the metaverse, helping create the next evolution of social technology.</p>
            <div className="mt-3">
              {/* Name input field*/}
              <div className="pb-4">
                <label className={`block text-sm pb-2 font-avenirRoman ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`} htmlFor="name">{formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}</label>
                <input className="border-2 border-gray-500 p-2 rounded-md lg:w-1/2 shadow-md focus:border-sky-500 focus:ring-sky-500 text-sm" type="text" name="name" placeholder="Full name" value={formik.values.name} onChange={formik.handleChange} onBlur={formik.handleBlur} />
              </div>
              {/* E-Mail input field*/}
              <div className="pb-4">
                <label className={`block text-sm pb-2 font-avenirRoman ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`} htmlFor="email">{formik.touched.email && formik.errors.email ? formik.errors.email : 'E-Mail'}</label>
                <input className="border-2 border-gray-500 p-2 rounded-md lg:w-1/2 shadow-md focus:border-sky-500 focus:ring-sky-500 text-sm" type="email" name="email" placeholder="Email address" value={formik.values.email} onChange={formik.handleChange} onBlur={formik.handleBlur} />
              </div>
              {/* Country input field*/}
              <div className="pb-4">
                <label className="block text-sm pb-2 font-avenirRoman" htmlFor="country">Country</label>
                <select className="border-2 border-gray-500 cursor-pointer p-2 rounded-md lg:w-1/2 shadow-md focus:border-sky-500 focus:ring-sky-500 text-sm" name="country" value={formik.values.country} onChange={formik.handleChange}>
                  <option>🇺🇸 United States</option>
                  <option>🇧🇪 Belgium</option>
                  <option>🇨🇳 China</option>
                  <option>🇫🇷 France</option>
                  <option>🇩🇪 Germany</option>
                  <option>🇮🇹 Italy</option>
                  <option>🇯🇵 Japan</option>
                  <option>🇿🇦 South Africa</option>
                  <option>🇹🇷 Turkey</option>
                  <option>🇷🇺 Russia</option>
                  <option>🇬🇧 United Kingdom</option>
                </select>
              </div>
              {/* Terms of Service */}
              <div className="pb-4">
                <label className={`block text-sm pb-2 font-avenirRoman ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`} htmlFor="terms">{formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms & Conditions'}</label>
                <div className="flex items-center gap-2">
                  <input className="lg:h-5 lg:w-5 text-blue-600/75 cursor-pointer shadown-md border-2 focus:border-blue-600/75 focus:ring-blue-600/75" type="checkbox" name="terms" value="checked" onChange={formik.handleChange} />
                  <p className="text-sm font-avenirRoman text-gray-500 pt-1">I agree to the Terms and Conditions.</p>
                </div>
              </div>
              <motion.button type="submit" className="bg-blue-600/75 font-metropolisSemiBold text-sm text-white py-3 mt-6 rounded-lg w-full shadow-sm" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.9 }}>
                Join The Community!
              </motion.button>
            </div>
          </div>
          <div className="relative flex-1">
            <Image src={metaverse} fill className="object-cover rounded-lg" alt="image" priority  sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw" />
          </div>
        </form>
      </main>
    </motion.div>
  )
}
